### PR TITLE
Add swab screen 

### PR DESCRIPTION
**Pull request by mozzy11**

### CODE REVIEW

**Comment by mozzy11** [comment]
image

**Comment by mozzy11** [comment]
hey @caseyi , @CalebSLane @rossumg  ,
This ready for review

**Comment by mozzy11** [comment]
Also fixed Summary Page toreturn Yes/No instead of True/False
image

**Review by CalebSLane — CHANGES_REQUESTED** [review]
application-dev.properties contains local dev paths when it shouldn't. Please remove.

prod/properties/locatorform-app.properties will need the security constraints for swab screen. Actually it might be better to move those "common" properties that should stay the same regardless of environment into src/main/resources/application.properties.

**Comment by mozzy11** [comment]
@CalebSLane That makes sense.
done

**Review by CalebSLane — APPROVED** [review]
Thanks @mozzy11, great work as always

**Pull request merged**
