### PR TITLE
Small UI changes to the Locator Form

### PR DESCRIPTION
**Pull request by mozzy11**

### CODE REVIEW

**Comment by mozzy11** [comment]
@CalebSLane @caseyi  
This is ready for review

**Comment by mozzy11** [comment]
see current out put 
[print.pdf](https://github.com/I-TECH-UW/Locator-Form/files/7339811/print.pdf)

**Comment by mozzy11** [comment]
sample print out 
[print.pdf](https://github.com/I-TECH-UW/Locator-Form/files/7339865/print.pdf)

**Review by CalebSLane — DISMISSED** [review]
Add translation for Nationality to fr,json please

**Comment by mozzy11** [comment]
hello @CalebSLane  , the french transaltion for nationality already exists [here](https://github.com/I-TECH-UW/Locator-Form/blob/develop/locator-form-frontend/src/i18n/fr.json#L73)

**Review by CalebSLane — APPROVED** [review]
Everything looks good!

**Pull request merged**
