### PR TITLE
add filters by role on the Health desk view  and improve layout

### PR DESCRIPTION
**Pull request by mozzy11**

### CODE REVIEW

**Comment by mozzy11** [comment]
1.added the filter by role for the following fields , so the PIO user cant see them
* Tesk kit Id 
* Emergency contact Information
* Resident /Non Resident
* Seat No.
* Symptoms
* Vaccine Details
2. I  improved the layout to look more like the above mock
3. Added a cancel/Reset Button

**Comment by mozzy11** [comment]
Helth desk View screen shot 
hd2
hd1

**Comment by mozzy11** [comment]
PIO user view screen shots 
pio2
pio

**Comment by mozzy11** [comment]
cc @CalebSLane  @caseyi

**Comment by mozzy11** [comment]
image

**Review by CalebSLane — APPROVED** [review]
thanks @mozzy11, looks good!

**Pull request merged**
